"""add capture_session rtms_stream_id

Revision ID: 0c2c1d52140a
Revises: 8375a3187bd9
Create Date: 2026-08-18 21:43:06.045709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '0c2c1d52140a'
down_revision: Union[str, None] = '8375a3187bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capture_session', sa.Column('rtms_stream_id', sa.String(length=128), nullable=True))
    op.create_index('ix_capsession_rtms_stream', 'capture_session', ['rtms_stream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_capsession_rtms_stream', table_name='capture_session')
    op.drop_column('capture_session', 'rtms_stream_id')
    # ### end Alembic commands ###
