"""initial schema

Revision ID: 513cbcbd3406
Revises: 
Create Date: 2026-08-01 23:35:26.732809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '513cbcbd3406'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('join_policy', sa.String(length=32), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_org_at', 'audit_log', ['org_id', 'at'], unique=False)
    op.create_table('calendar_connection',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('watch_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calconn_org', 'calendar_connection', ['org_id'], unique=False)
    op.create_table('meeting',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_meeting_id', sa.String(length=255), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meeting_org_start', 'meeting', ['org_id', 'scheduled_start'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_person_org', 'person', ['org_id'], unique=False)
    op.create_table('capture_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=4), nullable=False),
    sa.Column('state', sa.Enum('SCHEDULED', 'ACQUIRING', 'ACQUIRED', 'TRANSCRIBING', 'UNDERSTANDING', 'VERIFYING', 'REMEMBERING', 'PROPOSING', 'REPORTING', 'DONE', 'FAILED', name='capturestate', native_enum=False, length=32), nullable=False),
    sa.Column('disclosure_log', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_capsession_org_state', 'capture_session', ['org_id', 'state'], unique=False)
    op.create_table('audio_track',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('uri', sa.String(length=1000), nullable=False),
    sa.Column('participant_person_id', sa.String(length=36), nullable=True),
    sa.Column('participant_display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['participant_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audiotrack_session', 'audio_track', ['capture_session_id'], unique=False)
    op.create_table('consent_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consent_session', 'consent_record', ['capture_session_id'], unique=False)
    op.create_table('coverage_interval',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('modality', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('OK', 'DEGRADED', 'MISSING', name='coveragestatus', native_enum=False, length=16), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coverage_session', 'coverage_interval', ['capture_session_id'], unique=False)
    op.create_table('keyframe',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('valid_from_s', sa.Float(), nullable=False),
    sa.Column('valid_to_s', sa.Float(), nullable=False),
    sa.Column('image_uri', sa.String(length=1000), nullable=False),
    sa.Column('phash', sa.String(length=64), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=False),
    sa.Column('vlm_caption', sa.Text(), nullable=False),
    sa.Column('detected_entities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_keyframe_session_start', 'keyframe', ['capture_session_id', 'valid_from_s'], unique=False)
    op.create_table('knowledge_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('DECISION', 'COMMITMENT', 'REQUIREMENT', 'BLOCKER', 'QUESTION', 'FACT', name='knowledgetype', native_enum=False, length=16), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('owner_person_id', sa.String(length=36), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifecycle_state', sa.Enum('NEW', 'RECURRING', 'REOPENED', 'RESOLVED', 'SUPERSEDED', name='lifecyclestate', native_enum=False, length=16), nullable=False),
    sa.Column('confidence', sa.Enum('VERIFIED', 'PARTIALLY_SUPPORTED', 'AMBIGUOUS', 'UNSUPPORTED', name='confidence', native_enum=False, length=24), nullable=False),
    sa.Column('confidence_rationale', sa.Text(), nullable=False),
    sa.Column('overlaps_coverage_gap', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['owner_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ki_org_type_state', 'knowledge_item', ['org_id', 'type', 'lifecycle_state'], unique=False)
    op.create_index('ix_ki_session', 'knowledge_item', ['capture_session_id'], unique=False)
    op.create_table('participant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('platform_user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_participant_session', 'participant', ['capture_session_id'], unique=False)
    op.create_table('pipeline_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', name='jobstatus', native_enum=False, length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_status_runat', 'pipeline_job', ['status', 'run_at'], unique=False)
    op.create_table('proposed_action',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXECUTED', 'FAILED', name='actionstatus', native_enum=False, length=24), nullable=False),
    sa.Column('approved_by_person_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status NOT IN ('approved','executed') OR approved_by_person_id IS NOT NULL", name='ck_action_requires_approval'),
    sa.ForeignKeyConstraint(['approved_by_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_org_status', 'proposed_action', ['org_id', 'status'], unique=False)
    op.create_table('utterance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang_tags', sa.JSON(), nullable=False),
    sa.Column('asr_confidence', sa.Float(), nullable=False),
    sa.Column('attribution_confidence', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('repaired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_utterance_session_start', 'utterance', ['capture_session_id', 'start_s'], unique=False)
    op.create_table('correction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('utterance_id', sa.String(length=36), nullable=False),
    sa.Column('corrected_by_person_id', sa.String(length=36), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('training_consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['utterance_id'], ['utterance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_correction_org', 'correction', ['org_id'], unique=False)
    op.create_table('knowledge_edge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('from_item_id', sa.String(length=36), nullable=False),
    sa.Column('to_item_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('SUPERSEDES', 'CONTRADICTS', 'CONTINUES', 'RECURS', 'RESOLVES', name='edgekind', native_enum=False, length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('from_item_id != to_item_id', name='ck_edge_no_self'),
    sa.ForeignKeyConstraint(['from_item_id'], ['knowledge_item.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['to_item_id'], ['knowledge_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_from', 'knowledge_edge', ['from_item_id'], unique=False)
    op.create_index('ix_edge_to', 'knowledge_edge', ['to_item_id'], unique=False)
    op.create_table('knowledge_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_item_id', sa.String(length=36), nullable=False),
    sa.Column('utterance_id', sa.String(length=36), nullable=True),
    sa.Column('keyframe_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.CheckConstraint('(utterance_id IS NOT NULL) OR (keyframe_id IS NOT NULL)', name='ck_evidence_has_source'),
    sa.ForeignKeyConstraint(['keyframe_id'], ['keyframe.id'], ),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_item.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['utterance_id'], ['utterance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ke_item', 'knowledge_evidence', ['knowledge_item_id'], unique=False)
    op.create_table('utterance_keyframe',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('utterance_id', sa.String(length=36), nullable=False),
    sa.Column('keyframe_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['keyframe_id'], ['keyframe.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['utterance_id'], ['utterance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uk_utterance', 'utterance_keyframe', ['utterance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uk_utterance', table_name='utterance_keyframe')
    op.drop_table('utterance_keyframe')
    op.drop_index('ix_ke_item', table_name='knowledge_evidence')
    op.drop_table('knowledge_evidence')
    op.drop_index('ix_edge_to', table_name='knowledge_edge')
    op.drop_index('ix_edge_from', table_name='knowledge_edge')
    op.drop_table('knowledge_edge')
    op.drop_index('ix_correction_org', table_name='correction')
    op.drop_table('correction')
    op.drop_index('ix_utterance_session_start', table_name='utterance')
    op.drop_table('utterance')
    op.drop_index('ix_action_org_status', table_name='proposed_action')
    op.drop_table('proposed_action')
    op.drop_index('ix_job_status_runat', table_name='pipeline_job')
    op.drop_table('pipeline_job')
    op.drop_index('ix_participant_session', table_name='participant')
    op.drop_table('participant')
    op.drop_index('ix_ki_session', table_name='knowledge_item')
    op.drop_index('ix_ki_org_type_state', table_name='knowledge_item')
    op.drop_table('knowledge_item')
    op.drop_index('ix_keyframe_session_start', table_name='keyframe')
    op.drop_table('keyframe')
    op.drop_index('ix_coverage_session', table_name='coverage_interval')
    op.drop_table('coverage_interval')
    op.drop_index('ix_consent_session', table_name='consent_record')
    op.drop_table('consent_record')
    op.drop_index('ix_audiotrack_session', table_name='audio_track')
    op.drop_table('audio_track')
    op.drop_index('ix_capsession_org_state', table_name='capture_session')
    op.drop_table('capture_session')
    op.drop_index('ix_person_org', table_name='person')
    op.drop_table('person')
    op.drop_index('ix_meeting_org_start', table_name='meeting')
    op.drop_table('meeting')
    op.drop_index('ix_calconn_org', table_name='calendar_connection')
    op.drop_table('calendar_connection')
    op.drop_index('ix_audit_org_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('org')
    # ### end Alembic commands ###
