"""add longitudinal intelligence tables

Revision ID: 5cf0741b94d0
Revises: b2a1c7f5e9d0
Create Date: 2026-08-12 23:04:18.425869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '5cf0741b94d0'
down_revision: Union[str, None] = 'b2a1c7f5e9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_analysis_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Enum('ASSEMBLING', 'DETECTING', 'ASSESSING', 'AUDITING', 'NARRATING', 'RECOMMENDING', 'DONE', 'FAILED', name='longitudinalstate', native_enum=False, length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('coverage_disclosure', sa.JSON(), nullable=False),
    sa.Column('prompt_versions', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'period_start', 'period_end', name='uq_person_analysis_period')
    )
    op.create_index('ix_person_analysis_org_state', 'person_analysis_run', ['org_id', 'state'], unique=False)
    op.create_table('longitudinal_finding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('DECISION_TRAJECTORY', 'REPETITION', 'PROGRESS', name='findingkind', native_enum=False, length=24), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Enum('VERIFIED', 'PARTIALLY_SUPPORTED', 'AMBIGUOUS', 'UNSUPPORTED', name='confidence', native_enum=False, length=24), nullable=False),
    sa.Column('evidence_item_ids', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('finding_metadata', sa.JSON(), nullable=False),
    sa.Column('audit_status', sa.Enum('PENDING', 'SUPPORTED', 'PARTIALLY_SUPPORTED', 'UNSUPPORTED', name='findingauditstatus', native_enum=False, length=24), nullable=False),
    sa.Column('audit_rationale', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['person_analysis_run.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_longitudinal_finding_org_person', 'longitudinal_finding', ['org_id', 'person_id'], unique=False)
    op.create_index('ix_longitudinal_finding_run', 'longitudinal_finding', ['analysis_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_longitudinal_finding_run', table_name='longitudinal_finding')
    op.drop_index('ix_longitudinal_finding_org_person', table_name='longitudinal_finding')
    op.drop_table('longitudinal_finding')
    op.drop_index('ix_person_analysis_org_state', table_name='person_analysis_run')
    op.drop_table('person_analysis_run')
    # ### end Alembic commands ###
