"""add speaker_turn, session_speaker, utterance.speaker_cluster_id

Revision ID: 6dbb5b27ddb6
Revises: 41559b503ed5
Create Date: 2026-08-11 14:42:42.104380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '6dbb5b27ddb6'
down_revision: Union[str, None] = '41559b503ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_speaker',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('resolution_method', sa.Enum('ROSTER', 'VOICEPRINT', 'MANUAL', 'UNRESOLVED', name='speakerresolution', native_enum=False, length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capture_session_id', 'cluster_id', name='uq_session_speaker_cluster')
    )
    op.create_index('ix_sessionspeaker_session', 'session_speaker', ['capture_session_id'], unique=False)
    op.create_table('speaker_turn',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=False),
    sa.Column('end_s', sa.Float(), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_speakerturn_session_start', 'speaker_turn', ['capture_session_id', 'start_s'], unique=False)
    op.add_column('utterance', sa.Column('speaker_cluster_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utterance', 'speaker_cluster_id')
    op.drop_index('ix_speakerturn_session_start', table_name='speaker_turn')
    op.drop_table('speaker_turn')
    op.drop_index('ix_sessionspeaker_session', table_name='session_speaker')
    op.drop_table('session_speaker')
    # ### end Alembic commands ###
