"""add meeting external_calendar_event_id

Revision ID: 7e08993f29f5
Revises: a53c2d0da115
Create Date: 2026-08-02 17:13:45.620830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '7e08993f29f5'
down_revision: Union[str, None] = 'a53c2d0da115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('external_calendar_event_id', sa.String(length=255), nullable=True))
    op.create_index('ix_meeting_external_calendar_event', 'meeting', ['org_id', 'external_calendar_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meeting_external_calendar_event', table_name='meeting')
    op.drop_column('meeting', 'external_calendar_event_id')
    # ### end Alembic commands ###
