"""add llm_call, org budget, hnsw vector indexes

Adds the LLM cost-attribution ledger (`llm_call`) plus the per-org monthly
token ceiling that reads from it, and HNSW ANN indexes on the three vector
columns -- previously every `cosine_distance` ordering in app/api/chat.py and
app/agents/memory.py was a sequential scan.

HNSW needs pgvector >= 0.5.0. The dev/CI image (pgvector/pgvector:pg16) and
Cloud SQL both satisfy that; a much older pgvector would need ivfflat instead.

Revision ID: 8375a3187bd9
Revises: c1a2f6e8b3d4
Create Date: 2026-08-18 21:16:10.650226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '8375a3187bd9'
down_revision: Union[str, None] = 'c1a2f6e8b3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('capture_session_id', sa.String(length=36), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llmcall_org_at', 'llm_call', ['org_id', 'at'], unique=False)
    op.create_index('ix_llmcall_session', 'llm_call', ['capture_session_id'], unique=False)
    op.create_index('ix_ki_embedding_hnsw', 'knowledge_item', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('org', sa.Column('monthly_llm_token_budget', sa.Integer(), nullable=True))
    op.create_index('ix_person_voiceprint_hnsw', 'person', ['voiceprint'], unique=False, postgresql_using='hnsw', postgresql_ops={'voiceprint': 'vector_cosine_ops'})
    op.create_index('ix_sessionspeaker_embedding_hnsw', 'session_speaker', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessionspeaker_embedding_hnsw', table_name='session_speaker', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_person_voiceprint_hnsw', table_name='person', postgresql_using='hnsw', postgresql_ops={'voiceprint': 'vector_cosine_ops'})
    op.drop_column('org', 'monthly_llm_token_budget')
    op.drop_index('ix_ki_embedding_hnsw', table_name='knowledge_item', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_llmcall_session', table_name='llm_call')
    op.drop_index('ix_llmcall_org_at', table_name='llm_call')
    op.drop_table('llm_call')
    # ### end Alembic commands ###
