"""add org_connection table

Revision ID: 9ebd0f20f3f0
Revises: 7e08993f29f5
Create Date: 2026-08-05 17:19:34.892003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '9ebd0f20f3f0'
down_revision: Union[str, None] = '7e08993f29f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_connection',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_label', sa.String(length=320), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orgconn_org', 'org_connection', ['org_id'], unique=False)
    op.create_index('ix_orgconn_org_provider', 'org_connection', ['org_id', 'provider'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orgconn_org_provider', table_name='org_connection')
    op.drop_index('ix_orgconn_org', table_name='org_connection')
    op.drop_table('org_connection')
    # ### end Alembic commands ###
