"""add capture_session.video_uri

Revision ID: a44e9d4a94e5
Revises: 513cbcbd3406
Create Date: 2026-08-02 11:54:02.769849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'a44e9d4a94e5'
down_revision: Union[str, None] = '513cbcbd3406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capture_session', sa.Column('video_uri', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capture_session', 'video_uri')
    # ### end Alembic commands ###
