"""add glossary_term

Revision ID: a53c2d0da115
Revises: a44e9d4a94e5
Create Date: 2026-08-02 14:56:58.045276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'a53c2d0da115'
down_revision: Union[str, None] = 'a44e9d4a94e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_term',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('added_by_person_id', sa.String(length=36), nullable=True),
    sa.Column('source_correction_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['source_correction_id'], ['correction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_glossary_org', 'glossary_term', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_glossary_org', table_name='glossary_term')
    op.drop_table('glossary_term')
    # ### end Alembic commands ###
