"""add landing_lead

Revision ID: c1a2f6e8b3d4
Revises: d7ff84cbbaa3
Create Date: 2026-08-21 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'c1a2f6e8b3d4'
down_revision: Union[str, None] = 'd7ff84cbbaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_lead',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('DEMO', 'COLLABORATE', name='leadkind', native_enum=False, length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_landing_lead_kind_created', 'landing_lead', ['kind', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_landing_lead_kind_created', table_name='landing_lead')
    op.drop_table('landing_lead')
    # ### end Alembic commands ###
