"""add calendar_connection.teams_scope_granted

Revision ID: d40b31ce9047
Revises: 0c2c1d52140a
Create Date: 2026-08-26 17:21:25.153133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'd40b31ce9047'
down_revision: Union[str, None] = '0c2c1d52140a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'calendar_connection',
        sa.Column('teams_scope_granted', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_connection', 'teams_scope_granted')
    # ### end Alembic commands ###
