"""add_bot_session

Revision ID: d7ff84cbbaa3
Revises: 156253241ff2
Create Date: 2026-08-16 21:36:53.042550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'd7ff84cbbaa3'
down_revision: Union[str, None] = '156253241ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('join_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'JOINING', 'IN_LOBBY', 'LIVE', 'ENDED', 'FAILED', 'LOBBY_TIMEOUT', name='botstatus', native_enum=False, length=32), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lobby_timeout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_blob_uri', sa.String(length=1000), nullable=True),
    sa.Column('capture_session_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_session_id'], ['capture_session.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_botsession_org_status', 'bot_session', ['org_id', 'status'], unique=False)
    op.create_index('ix_botsession_scheduled_start', 'bot_session', ['scheduled_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_botsession_scheduled_start', table_name='bot_session')
    op.drop_index('ix_botsession_org_status', table_name='bot_session')
    op.drop_table('bot_session')
    # ### end Alembic commands ###
